/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedCleanerIndexRouteImport } from './routes/_authenticated/cleaner/index'
import { Route as AuthenticatedClientIndexRouteImport } from './routes/_authenticated/client/index'
import { Route as AuthenticatedClientNewOrderRouteImport } from './routes/_authenticated/client/new-order'
import { Route as AuthenticatedClientOrdersRouteImport } from './routes/_authenticated/client/orders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCleanerIndexRoute =
  AuthenticatedCleanerIndexRouteImport.update({
    id: '/cleaner/',
    path: '/cleaner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientIndexRoute =
  AuthenticatedClientIndexRouteImport.update({
    id: '/client/',
    path: '/client/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientNewOrderRoute =
  AuthenticatedClientNewOrderRouteImport.update({
    id: '/client/new-order',
    path: '/client/new-order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientOrdersRoute =
  AuthenticatedClientOrdersRouteImport.update({
    id: '/client/orders',
    path: '/client/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client/new-order': typeof AuthenticatedClientNewOrderRoute
  '/client/orders': typeof AuthenticatedClientOrdersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/cleaner/': typeof AuthenticatedCleanerIndexRoute
  '/client/': typeof AuthenticatedClientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/client/new-order': typeof AuthenticatedClientNewOrderRoute
  '/client/orders': typeof AuthenticatedClientOrdersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/cleaner': typeof AuthenticatedCleanerIndexRoute
  '/client': typeof AuthenticatedClientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/client/new-order': typeof AuthenticatedClientNewOrderRoute
  '/_authenticated/client/orders': typeof AuthenticatedClientOrdersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/cleaner/': typeof AuthenticatedCleanerIndexRoute
  '/_authenticated/client/': typeof AuthenticatedClientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/client/new-order'
    | '/client/orders'
    | '/admin/'
    | '/cleaner/'
    | '/client/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/client/new-order'
    | '/client/orders'
    | '/admin'
    | '/cleaner'
    | '/client'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/client/new-order'
    | '/_authenticated/client/orders'
    | '/_authenticated/admin/'
    | '/_authenticated/cleaner/'
    | '/_authenticated/client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cleaner/': {
      id: '/_authenticated/cleaner/'
      path: '/cleaner'
      fullPath: '/cleaner/'
      preLoaderRoute: typeof AuthenticatedCleanerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/': {
      id: '/_authenticated/client/'
      path: '/client'
      fullPath: '/client/'
      preLoaderRoute: typeof AuthenticatedClientIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/new-order': {
      id: '/_authenticated/client/new-order'
      path: '/client/new-order'
      fullPath: '/client/new-order'
      preLoaderRoute: typeof AuthenticatedClientNewOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/client/orders': {
      id: '/_authenticated/client/orders'
      path: '/client/orders'
      fullPath: '/client/orders'
      preLoaderRoute: typeof AuthenticatedClientOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientNewOrderRoute: typeof AuthenticatedClientNewOrderRoute
  AuthenticatedClientOrdersRoute: typeof AuthenticatedClientOrdersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedCleanerIndexRoute: typeof AuthenticatedCleanerIndexRoute
  AuthenticatedClientIndexRoute: typeof AuthenticatedClientIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientNewOrderRoute: AuthenticatedClientNewOrderRoute,
  AuthenticatedClientOrdersRoute: AuthenticatedClientOrdersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedCleanerIndexRoute: AuthenticatedCleanerIndexRoute,
  AuthenticatedClientIndexRoute: AuthenticatedClientIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
